### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/G#155]
### ✨ Describe

알림 기능을 만들어보겠쥽니다

### ✅ Tasks

- [x] notification entity, repository
- [ ] read
- [ ] create 어디서할지 결정해서 넣깅~~
- [ ] socket notification 보내는거
- [ ] notification subscribe도 해야대지않나
- [x] 아 맞네 현재 있는 notification 조회

### 🙋🏻 More

네트워크 소켓 수행개꿀
